# idea自带的http client工具, 可以测试接口
GET http://localhost:8888/member/hello
Accept: application/json

###
POST http://localhost:8888/member/member/register
Content-type: application/x-www-form-urlencoded

mobile=11122223333

###
POST http://localhost:8888/member/member/send-code
Content-type: application/x-www-form-urlencoded

mobile=11122223333

###
###
POST http://localhost:8888/member/member/login
Content-type: application/x-www-form-urlencoded

mobile=11122223333&code=8888